### ISSUE TITLE
BringUp Failure at "Trust Certificates" Stage

### ISSUE THREAD

**Issue by BhojaRavi** [lamw/vcf-automated-lab-deployment#11]
Using the script as is with all configuration parameters set. The deployment of Nested ESXi Hosts (VMs) is successful with the CloudBuilder Appliance.

The BringUp process kicks in and fails stage of "Trust Certificates"

<img width="2466" alt="image" src="https://github.com/lamw/vcf-automated-lab-deployment/assets/160106372/a6ccc21f-0917-42d0-87d3-fd79a593b009">

I further digged in to the .JSON file that is generated to add the SSH & SSL Thumbprint. However, ran into a lot of validation issues when I restarted by submitted the updated JSON file.

Is there a way to update JSON file on the CloudBuilder with the SSH & SSL Thumbprint so that I can retry from where it left ?

Also I am able to reproduce the issue while doing multiple install attempts.

**Comment by lamw** [comment]
The error can be miss-leading since `skipEsxThumbprintValidation` is set to true. The issue, which this has come up is that you may not have properly configured FQDN for your ESXi host (ensure FQDN are fully resolvable in DNS as that part of the validation CB performs

**Comment by BhojaRavi** [comment]
Thanks. That was a good catch.

I had a working DNS entry. Not sure what messed up during reboots. I fixed the DNS and now pass the stage.

Keeping fingers crossed.
