### ISSUE TITLE
vcf-m01-vc01 (vCenter VM) - Failed to configure Network

### ISSUE THREAD

**Issue by BhojaRavi** [lamw/vcf-automated-lab-deployment#13]
Thanks for the help on previous questions. I was able to make further progress and now it is stuck at "Failed to configure network" as seen below.

![image](https://github.com/lamw/vcf-automated-lab-deployment/assets/160106372/f16c34d4-5f9b-43bc-b12c-c2d236af7ebc)

Also I see a warning which indicates the OS selection isn't right.

![image](https://github.com/lamw/vcf-automated-lab-deployment/assets/160106372/adc2e628-e328-4c70-9c4b-e5ed9295450a)

This time I made sure that the DNS entries are working with forward and reverse lookups.

I also made an attempt to change the guest OS type selection but the warning remains. Guessing that the vmxnet driver is a mis-match and causing the network configuration issue.

Please advise.

**Comment by BhojaRavi** [comment]
Quick question: Might sound basic but wanted to confirm.
Is the vCenter Image used here is picked up from the CloudBuilder OVA or Is that bundled with the NestedESXi OVA ?

I was unable to extract the NestedESXi OVA hence checking. Please advise.

**Comment by BhojaRavi** [comment]
Also I am able to reproduce the error on CloudBuilder v5.0. Trying to findout what I may be missing here.

**Comment by BhojaRavi** [comment]
Just to rule out issue on the version, I tried a CloudBuilder v4.5 and I still see the issue. Curious to know if I'm missing something.

**Comment by lamw** [comment]
This is probably due to not properly setting up your physical networking as outlined in the requirements. Please review ESXi networking ...

**Comment by BhojaRavi** [comment]
Thanks William. I am able to get to the next stage of fixing Network issues on vCenter server. Now I have come this far, I don't want to give up and complete this setup with success.

After the vCenter install, it is somehow unable to proceed to next step on the validation and in a few minutes it removes starts a reinstall of the VM. This way it goes into a loop. I tried reviewing the debug logs but didn't find anything significant other than the below message.

2024-02-21T18:54:17.681+0000 [bringup,0335bdc25581f03c,a9b6] ERROR [c.v.e.s.o.model.error.ErrorFactory,pool-2-thread-5] [KL98DF] VCF_VSPHERE_VCENTER_INSTALLATION_FAILED vCenter installation failed. 

Appreciate your time helping me on this.

**Comment by BhojaRavi** [comment]
Finally, I figured out it was NTP that the installer wasn't able to get to. 

My closing comment: Thanks for putting this automation together, helps a lot and saves a lot of manual work.

**Comment by BhojaRavi** [comment]
Finally, I figured out it was NTP that the installer wasn't able to get to.

My closing comment: Thanks for putting this automation together, helps a lot and saves a lot of manual work.
