### ISSUE TITLE
OVA Images from Fling past 8.0GA have importation errors "Not a Valid Template"

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [lamw/vcf-automated-lab-deployment#15]
Experienced this just importing the fling, this code utilizes an OVA image that has issues with deployment figured i would point this out here. 

![image](https://github.com/lamw/vcf-automated-lab-deployment/assets/1888195/330f4452-9265-4276-84e9-900321e0cc9c)

**Comment by lamw** [comment]
Have you tried from a different system or browser? The downloads works for me and several others have confirmed but I've still see some reports where the download may still be corrupted but I'm unable to reproduce on several different systems

**Comment by VDI-Tech-Guy** [comment]
Also tested multiple systems across multiple states (all windows based clients) tried Edge/Firefox/Chrome, all led to the invalid template image.

**Comment by VDI-Tech-Guy** [comment]
@lamw -  Heres an idea can you link me a copy of your working OVA so i can verify that the issue is the OVA downloaded and not some weird configuration change or vCenter/ESXi Build thing?

**Comment by VDI-Tech-Guy** [comment]
Issue solved with newer uploads to Flings the correct MD5s for the downloads for 8.0U2B are below

09c744e0c0cc9348c6bedc70dfe07055 Nested_ESXi8.0u2b_Appliance_Template_v1.ova
34772ee5e88f727a7c61cb05006057dc Nested_ESXi8.0u2b_Appliance_Template_v1.ova-dl.zip

The main issue was corrupted images  this can be closed out.
