### ISSUE TITLE
Update Code from Blog as current code missing "clusterImageEnabled": true

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [lamw/vcf-automated-lab-deployment#16]
When Using 5.1.1 - Ended up with error that was in blog
https://williamlam.com/2024/03/quick-tip-clusterimageenabled-property-required-for-json-deployment-in-vmware-cloud-foundation-vcf-5-1-1.html

This hasnt been added to the code would recommend it (Looks like there is a pull request but hasnt been implemented)

**Comment by lamw** [comment]
Thanks for reporting this! Given the number of changes from 5.1.0->5.1.1 and OSA/ESA, I need to refactor the code to handle all these scenarios. Its on my todo but have a huge backlog of things for my day to day job, so we'll see when I get to it

**Comment by lamw** [comment]
Resolved w/latest update
