### ISSUE TITLE
Nested ESXi VMs for Workload Domain have same names as the Management Domain

### ISSUE THREAD

**Issue by GBTait** [lamw/vcf-automated-lab-deployment#9]
Original names in the script

# Nested ESXi VMs for Workload Domain
    "vcf-m01-esx01"   = "172.17.31.189"
    "vcf-m01-esx02"   = "172.17.31.190"
    "vcf-m01-esx03"   = "172.17.31.191"
    "vcf-m01-esx04"   = "172.17.31.192"

VM Names should be 

# Nested ESXi VMs for Workload Domain
    "vcf-m01-esx05"   = "172.17.31.189"
    "vcf-m01-esx06"   = "172.17.31.190"
    "vcf-m01-esx07"   = "172.17.31.191"
    "vcf-m01-esx08"   = "172.17.31.192"

or

# Nested ESXi VMs for Workload Domain
    "vcf-w01-esx01"   = "172.17.31.189"
    "vcf-w01-esx02"   = "172.17.31.190"
    "vcf-w01-esx03"   = "172.17.31.191"
    "vcf-w01-esx04"   = "172.17.31.192"

**Comment by lamw** [comment]
Thanks for reporting. I've just fixed
